services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: P4ssw0rd
      POSTGRES_DB: timetracker
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build: .
    ports:
      - "3100:3100"
    environment:
      DATABASE_URL: postgres://admin:P4ssw0rd@postgres:5432/timetracker
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:
